package com.sme.afs.service;

import com.sme.afs.config.BlobUrlProperties;
import com.sme.afs.model.BlobUrl;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.security.SecureRandom;
import java.time.Clock;
import java.time.OffsetDateTime;
import java.util.Base64;

/**
 * Service for generating and validating cryptographically secure tokens for blob URLs.
 * Uses SecureRandom for token generation and URL-safe Base64 encoding.
 */
@Service
@Slf4j
public class TokenService {

    private final BlobUrlProperties blobUrlProperties;
    private final Clock clock;
    private static final SecureRandom SECURE_RANDOM = new SecureRandom();
    private static final Base64.Encoder URL_ENCODER = Base64.getUrlEncoder().withoutPadding();

    @Autowired
    public TokenService(BlobUrlProperties blobUrlProperties, Clock clock) {
        this.blobUrlProperties = blobUrlProperties;
        this.clock = clock;
    }

    // Backward-compatible constructor for tests and manual instantiation
    public TokenService(BlobUrlProperties blobUrlProperties) {
        this(blobUrlProperties, Clock.systemDefaultZone());
    }

    /**
     * Generates a cryptographically secure random token for blob URLs.
     * Uses SecureRandom with URL-safe Base64 encoding to ensure tokens are
     * unpredictable and safe for use in URLs.
     *
     * @return A secure, URL-safe token string
     */
    public String generateSecureToken() {
        byte[] tokenBytes = new byte[blobUrlProperties.getTokenLength()];
        SECURE_RANDOM.nextBytes(tokenBytes);
        
        // Use URL-safe Base64 encoding (no padding) for clean URLs
        String token = URL_ENCODER.encodeToString(tokenBytes);
        
        log.debug("Generated secure token of length: {}", token.length());
        return token;
    }

    /**
     * Validates the format and structure of a token.
     * Checks that the token is properly formatted and has the expected characteristics
     * of a token generated by this service.
     *
     * @param token The token to validate
     * @return true if the token format is valid, false otherwise
     */
    public boolean validateTokenFormat(String token) {
        if (token == null || token.trim().isEmpty()) {
            log.debug("Token validation failed: null or empty token");
            return false;
        }

        // Check length - Base64 encoding of tokenLength bytes should produce a predictable length
        int n = blobUrlProperties.getTokenLength();
        int expectedLength = (n / 3) * 4 + ((n % 3 == 0) ? 0 : (n % 3 + 1));

        if (token.length() != expectedLength) {
            log.debug("Token validation failed: invalid length {} (expected {}-{})",
                    token.length(), expectedLength, expectedLength);
            return false;
        }

        // Check that token contains only URL-safe Base64 characters
        if (!token.matches("^[A-Za-z0-9_-]+$")) {
            log.debug("Token validation failed: contains invalid characters");
            return false;
        }

        return true;
    }

    /**
     * Checks if a blob URL has expired based on its expiration timestamp.
     *
     * @param blobUrl The blob URL entity to check
     * @return true if the blob URL has expired, false otherwise
     */
    public boolean isTokenExpired(BlobUrl blobUrl) {
        if (blobUrl == null) {
            return true;
        }
        
        boolean expired = blobUrl.isExpiredAt(OffsetDateTime.now(clock));
        log.debug("Token {} expiration check: {}", maskToken(blobUrl.getToken()), expired ? "EXPIRED" : "ACTIVE");
        return expired;
    }

    /**
     * Validates that a token exists and is not expired.
     * This is a convenience method that combines format validation with expiration checking.
     *
     * @param token The token string to validate
     * @param blobUrl The blob URL entity associated with the token (can be null)
     * @return true if the token is valid and not expired, false otherwise
     */
    public boolean validateToken(String token, BlobUrl blobUrl) {
        if (!validateTokenFormat(token)) {
            return false;
        }
        
        if (blobUrl == null) {
            log.debug("Token validation failed: no associated blob URL found");
            return false;
        }
        
        if (isTokenExpired(blobUrl)) {
            log.debug("Token validation failed: blob URL has expired");
            return false;
        }
        
        return true;
    }

    /**
     * Validates the configuration for the `TokenService` during application initialization.
     * Ensures the `tokenLength` property of `blobUrlProperties` is set to a minimum required value.
     * <p>
     * This method is annotated with `@PostConstruct` to be executed after the dependency injection
     * is complete, but before the class is put into service.
     *
     * @throws IllegalStateException if the configured `blobUrl.tokenLength` is less than 16 bytes
     */
    @jakarta.annotation.PostConstruct
    void validateConfig() {
        int len = blobUrlProperties.getTokenLength();
        if (len < 16) {
            throw new IllegalStateException("blobUrl.tokenLength must be >= 16 bytes");
        }
    }

    private static String maskToken(String token) {
        if (token == null || token.length() < 6) return "****";
        return token.substring(0, 3) + "..." + token.substring(token.length() - 3);
    }
}